language: python
os: linux
env:
  global:
    # - CIBW_SKIP=cp34-*
    - CIBW_BUILD=cp3?-*
    - CIBW_MANYLINUX_X86_64_IMAGE=manylinux1
    - CIBW_MANYLINUX_I686_IMAGE=manylinux1
    - TWINE_USERNAME=__token__

addons:
  homebrew:
    packages: gcc

jobs:
  include:
    - services: docker
    - os: osx
      # - addons:
      #   - homebrew:
      #     - packages:
      #       - gcc
      before_install:
        # - brew install llvm libomp
        # - export CXX=/usr/local/opt/llvm/bin/clang++
        # - export CC=/usr/local/opt/llvm/bin/clang
        # - brew update
        # - brew install gcc || brew link --overwrite gcc
        # - brew upgrade --verbose
        - export CC=gcc
        - export CXX=g++
      language: generic
      env: MACOSX_DEPLOYMENT_TARGET=10.9
    - os: windows
      language: bash
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python/Scripts:$PATH"
install:
  - python -m pip install -U setuptools wheel twine cibuildwheel==1.1.0
script:
  - python -m cibuildwheel --output-dir ./wheelhouse
  - ls wheelhouse
after_success:
  - if [[ $TRAVIS_TAG ]]; then python3 -m twine upload wheelhouse/*.whl; fi
